### PR TITLE
#163249327 User Registration Endpoint

### PR DESCRIPTION
**Pull request by dennisdnyce**
**What does this PR do?**
Enables a user to signup for an account and generates a session token for the user through the provided email address.

**Description of the tasks to be achieved**
Have the following goals achieved:
- creates user signup POST endpoint
- test the user registration POST endpoint

**How should this be manually tested?**

1. clone the git repo http://github.com/dennisdnyce/Questioner.git on your project folder.

2. cd Questioner

3. git checkout ft-challenge3-register-user-163249327

4. open terminal and execute ---> py.test --cov app/ tests/

**What are the relevant pivotal tracker stories?**
https://www.pivotaltracker.com/n/projects/2235504
#163249327

**Screenshots**
register
register test

### CODE REVIEW

**Comment by bencyn** [comment]
Look good

**Comment by emdeechege** [comment]
Looks great

**Comment by dennisdnyce** [comment]
> Looks good

asante

**Comment by dennisdnyce** [comment]
> Looks good

thank you

**Pull request merged**
